remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
#title: aaa Brainy v2
#description: bbb Qui trovi tutte le FAQ, guide e risorse utili.
url: https://brainyrms-com.github.io/documentation/